define([], function() {
  return {
    "userLang": "fr-fr",
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "EmailLabel": "Courriel",
    "ReasonOneLabel": "Quelle est votre raison principale pour soumettre un billet?",
    "ReasonTwoLabel": "Reason 2 Label (translate)",
    "DescriptionLabel": "Description",
    "PageLabel": "Adresse Web (le cas échéant)",
    "AttachLabel": "Joindre un fichier",
    "DateLabel": "Date Range",
    "EmailToLabel": "Envoyer le rapport à",
    "SubmitLabel": "Envoyer",
    "ReasonIssue": "Je rencontre un problème sur gcéchange",
    "ReasonAssistance": "J'ai besoin d'aide avec gcéchange",
    "ReasonData": "Je souhaite obtenir les statistiques de ma page",
    "ReasonOther": "Autre (veuillez préciser)",
    "MessageSuccess": "Votre billet a été soumis.",
    "MessageError": "Un problème est survenu; veuillez réessayer plus tard.",
    "MessageButtonResubmit": "Envoyer",
    "LoadingSubmitTicket": "Envoi du billet...",
    "SelectPlaceHolder": "Choisir une option",
  }
});